# Generated by Django 5.1.6 on 2025-02-12 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon_class', models.CharField(help_text="FontAwesome icon class (e.g., 'fas fa-truck')", max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='ALFA RECOVERY Ltd', max_length=100)),
                ('phone_number', models.CharField(default='+44 7722 015702', max_length=20)),
                ('whatsapp_number', models.CharField(default='+44 7722 015702', max_length=20)),
                ('address', models.CharField(default='Dean Rd, Avonmouth, Bristol BS11 8AT', max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('operating_hours', models.CharField(default='24/7', max_length=100)),
                ('facebook_link', models.URLField(blank=True)),
                ('instagram_link', models.URLField(blank=True)),
                ('meta_description', models.TextField(default='24/7 Vehicle Recovery & Roadside Assistance in the UK. Professional towing and breakdown services.', max_length=160)),
                ('meta_keywords', models.CharField(default='vehicle recovery, roadside assistance, towing service, car breakdown, UK', max_length=255)),
                ('google_maps_embed', models.TextField(blank=True, help_text='Paste your Google Maps embed code here')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
